# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: stock-crawler_development
  pool: 5
  username: sc-server-admin
  password: sc-admin-pass

test:
  adapter: postgresql
  encoding: unicode
  database: stock-crawler_test
  pool: 5
  username: sc-server-admin
  password: sc-admin-pass

production:
  adapter: postgresql
  encoding: unicode
  database: stock-crawler_production
  pool: 5
  username: sc-server-admin
  password: sc-admin-pass